name: PlayerLeashing
description: A simple Minecraft plugin for vanilla and SMP servers, which makes it possible to leash a player
author: HIlight3R
version: ${version}

api-version: 1.17
main: me.hilight3r.playerleashing.PlayerLeashing

permissions:
  playerleashing.use:
    description: Allows you to leash player
  playerleashing.*:
    description: All the above permissions
    children:
      playerleashing.use: true
